# Generated by Django 5.1.1 on 2024-09-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machinezz_delete_machine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machinezz',
            new_name='Machine',
        ),
    ]
