# Generated by Django 5.1.1 on 2024-09-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_machinezz_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='сategory',
            new_name='category',
        ),
    ]
