# Generated by Django 5.1.1 on 2024-09-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_сategory_catalogue_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
