# Generated by Django 5.1.1 on 2024-09-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'category': 'sco'}, on_delete=django.db.models.deletion.RESTRICT, related_name='serviced_machines', to='api.catalogue', verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('engine_hours', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=100, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказа-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenances', to='api.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'category': 'man'}, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_types', to='api.catalogue', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(blank=True, limit_choices_to={'category': 'sco'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenances', to='api.catalogue', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
    ]
