# Generated by Django 5.1.1 on 2024-09-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_machine_service_company_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('engine_hours', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(default='', verbose_name='Запасные части')),
                ('restoration_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(editable=False, verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claims', to='api.machine', verbose_name='Машина')),
                ('malfunction_node', models.ForeignKey(limit_choices_to={'category': 'mfn'}, on_delete=django.db.models.deletion.RESTRICT, related_name='malfunction_nodes', to='api.catalogue', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'category': 'rec'}, on_delete=django.db.models.deletion.RESTRICT, related_name='recovery_methods', to='api.catalogue', verbose_name='Метод восстановления')),
                ('service_company', models.ForeignKey(blank=True, limit_choices_to={'category': 'sco'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='claims', to='api.catalogue', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
