# Generated by Django 5.1.1 on 2024-09-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_claim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogue',
            new_name='Catalog',
        ),
    ]
