# Generated by Django 5.1.1 on 2024-09-16 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_catalogue_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.CharField(choices=[('tec', 'Модель техники'), ('eng', 'Модель двигателя'), ('trm', 'Модель трансмиссии'), ('lda', 'Модель ведущего моста'), ('sta', 'Модель управляемого моста'), ('man', 'Вид ТО'), ('mfn', 'Узел отказа'), ('rec', 'Способ восстановления')], max_length=3, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 's'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'role': 's'}, on_delete=django.db.models.deletion.RESTRICT, related_name='serviced_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 's'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
